# == Schema Information
#
# Table name: room_subjects
#
#  id         :integer          not null, primary key
#  name       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RoomSubjectsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RoomSubject. As you add validations to RoomSubject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RoomSubjectsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all room_subjects as @room_subjects" do
      room_subject = RoomSubject.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:room_subjects)).to eq([room_subject])
    end
  end

  describe "GET #show" do
    it "assigns the requested room_subject as @room_subject" do
      room_subject = RoomSubject.create! valid_attributes
      get :show, {:id => room_subject.to_param}, valid_session
      expect(assigns(:room_subject)).to eq(room_subject)
    end
  end

  describe "GET #new" do
    it "assigns a new room_subject as @room_subject" do
      get :new, {}, valid_session
      expect(assigns(:room_subject)).to be_a_new(RoomSubject)
    end
  end

  describe "GET #edit" do
    it "assigns the requested room_subject as @room_subject" do
      room_subject = RoomSubject.create! valid_attributes
      get :edit, {:id => room_subject.to_param}, valid_session
      expect(assigns(:room_subject)).to eq(room_subject)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RoomSubject" do
        expect {
          post :create, {:room_subject => valid_attributes}, valid_session
        }.to change(RoomSubject, :count).by(1)
      end

      it "assigns a newly created room_subject as @room_subject" do
        post :create, {:room_subject => valid_attributes}, valid_session
        expect(assigns(:room_subject)).to be_a(RoomSubject)
        expect(assigns(:room_subject)).to be_persisted
      end

      it "redirects to the created room_subject" do
        post :create, {:room_subject => valid_attributes}, valid_session
        expect(response).to redirect_to(RoomSubject.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved room_subject as @room_subject" do
        post :create, {:room_subject => invalid_attributes}, valid_session
        expect(assigns(:room_subject)).to be_a_new(RoomSubject)
      end

      it "re-renders the 'new' template" do
        post :create, {:room_subject => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested room_subject" do
        room_subject = RoomSubject.create! valid_attributes
        put :update, {:id => room_subject.to_param, :room_subject => new_attributes}, valid_session
        room_subject.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested room_subject as @room_subject" do
        room_subject = RoomSubject.create! valid_attributes
        put :update, {:id => room_subject.to_param, :room_subject => valid_attributes}, valid_session
        expect(assigns(:room_subject)).to eq(room_subject)
      end

      it "redirects to the room_subject" do
        room_subject = RoomSubject.create! valid_attributes
        put :update, {:id => room_subject.to_param, :room_subject => valid_attributes}, valid_session
        expect(response).to redirect_to(room_subject)
      end
    end

    context "with invalid params" do
      it "assigns the room_subject as @room_subject" do
        room_subject = RoomSubject.create! valid_attributes
        put :update, {:id => room_subject.to_param, :room_subject => invalid_attributes}, valid_session
        expect(assigns(:room_subject)).to eq(room_subject)
      end

      it "re-renders the 'edit' template" do
        room_subject = RoomSubject.create! valid_attributes
        put :update, {:id => room_subject.to_param, :room_subject => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested room_subject" do
      room_subject = RoomSubject.create! valid_attributes
      expect {
        delete :destroy, {:id => room_subject.to_param}, valid_session
      }.to change(RoomSubject, :count).by(-1)
    end

    it "redirects to the room_subjects list" do
      room_subject = RoomSubject.create! valid_attributes
      delete :destroy, {:id => room_subject.to_param}, valid_session
      expect(response).to redirect_to(room_subjects_url)
    end
  end

end
